name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3.5.0
      with:
       go-version: '1.20'
    - uses: actions/checkout@v3
    - name: Build
      run: make build
    - name: Unit Test
      run: make test
      